[2024-05-10T09:04:37.258+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T09:04:37.283+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.spark manual__2024-05-10T07:47:08.649616+00:00 [queued]>
[2024-05-10T09:04:37.290+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.spark manual__2024-05-10T07:47:08.649616+00:00 [queued]>
[2024-05-10T09:04:37.291+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-05-10T09:04:37.301+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark> on 2024-05-10 07:47:08.649616+00:00
[2024-05-10T09:04:37.308+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=264) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T09:04:37.310+0000] {standard_task_runner.py:63} INFO - Started process 266 to run task
[2024-05-10T09:04:37.308+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'spark', 'manual__2024-05-10T07:47:08.649616+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpf894znfo']
[2024-05-10T09:04:37.310+0000] {standard_task_runner.py:91} INFO - Job 335: Subtask spark
[2024-05-10T09:04:37.320+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-10T09:04:37.345+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.spark manual__2024-05-10T07:47:08.649616+00:00 [running]> on host 412f8d774d35
[2024-05-10T09:04:37.415+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='spark' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T07:47:08.649616+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T07:47:08.649616+00:00'
[2024-05-10T09:04:37.417+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T09:04:37.434+0000] {spark_submit.py:271} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-05-10T09:04:37.435+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --verbose src/spark.py
[2024-05-10T09:04:37.509+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-05-10T09:04:37.510+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2024-05-10T09:04:37.511+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T09:04:37.517+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --verbose src/spark.py. Error code is: 1.
[2024-05-10T09:04:37.521+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=spark, run_id=manual__2024-05-10T07:47:08.649616+00:00, execution_date=20240510T074708, start_date=20240510T090437, end_date=20240510T090437
[2024-05-10T09:04:37.532+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 335 for task spark (Cannot execute: spark-submit --master yarn --name arrow-spark --verbose src/spark.py. Error code is: 1.; 266)
[2024-05-10T09:04:37.564+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T09:04:37.581+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T09:04:37.583+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
