[2024-05-10T09:09:38.697+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T09:09:38.720+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.spark manual__2024-05-10T07:47:08.649616+00:00 [queued]>
[2024-05-10T09:09:38.727+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.spark manual__2024-05-10T07:47:08.649616+00:00 [queued]>
[2024-05-10T09:09:38.727+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-05-10T09:09:38.737+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark> on 2024-05-10 07:47:08.649616+00:00
[2024-05-10T09:09:38.744+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=442) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T09:09:38.745+0000] {standard_task_runner.py:63} INFO - Started process 444 to run task
[2024-05-10T09:09:38.744+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'spark', 'manual__2024-05-10T07:47:08.649616+00:00', '--job-id', '336', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmpgcf_zanj']
[2024-05-10T09:09:38.746+0000] {standard_task_runner.py:91} INFO - Job 336: Subtask spark
[2024-05-10T09:09:38.756+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-10T09:09:38.784+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.spark manual__2024-05-10T07:47:08.649616+00:00 [running]> on host 412f8d774d35
[2024-05-10T09:09:38.857+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='spark' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T07:47:08.649616+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T07:47:08.649616+00:00'
[2024-05-10T09:09:38.859+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T09:09:38.883+0000] {spark_submit.py:271} INFO - Could not load connection string spark_default, defaulting to yarn
[2024-05-10T09:09:38.885+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark --verbose src/spark.py
[2024-05-10T09:09:38.984+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-05-10T09:09:38.984+0000] {spark_submit.py:571} INFO - JAVA_HOME is not set
[2024-05-10T09:09:38.985+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T09:09:38.990+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark --verbose src/spark.py. Error code is: 1.
[2024-05-10T09:09:38.993+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=spark, run_id=manual__2024-05-10T07:47:08.649616+00:00, execution_date=20240510T074708, start_date=20240510T090938, end_date=20240510T090938
[2024-05-10T09:09:39.002+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 336 for task spark (Cannot execute: spark-submit --master yarn --name arrow-spark --verbose src/spark.py. Error code is: 1.; 444)
[2024-05-10T09:09:39.039+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T09:09:39.056+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T09:09:39.058+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
