[2024-05-10T10:12:27.214+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T10:12:27.237+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.clean_api_data manual__2024-05-10T09:58:46.082243+00:00 [queued]>
[2024-05-10T10:12:27.243+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.clean_api_data manual__2024-05-10T09:58:46.082243+00:00 [queued]>
[2024-05-10T10:12:27.244+0000] {taskinstance.py:2306} INFO - Starting attempt 13 of 16
[2024-05-10T10:12:27.254+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): clean_api_data> on 2024-05-10 09:58:46.082243+00:00
[2024-05-10T10:12:27.260+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=674) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T10:12:27.260+0000] {standard_task_runner.py:63} INFO - Started process 676 to run task
[2024-05-10T10:12:27.260+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'clean_api_data', 'manual__2024-05-10T09:58:46.082243+00:00', '--job-id', '363', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmplre54pnp']
[2024-05-10T10:12:27.261+0000] {standard_task_runner.py:91} INFO - Job 363: Subtask clean_api_data
[2024-05-10T10:12:27.271+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-10T10:12:27.297+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.clean_api_data manual__2024-05-10T09:58:46.082243+00:00 [running]> on host dbfcb70dcca2
[2024-05-10T10:12:27.363+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='clean_api_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T09:58:46.082243+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T09:58:46.082243+00:00'
[2024-05-10T10:12:27.364+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T10:12:27.427+0000] {logging_mixin.py:188} INFO -                                                title  ...                                           keywords
0  Shear capacity of high performance fiber reinf...  ...  [Fiber content, High performance fiber reinfor...
1                   Mutation operators in BPMN model  ...        [BPMN, Mutation Operator, Mutation Testing]
2  Characteristics and catalytic properties of Ni...  ...  [CO2 hydrogenation, Methanation, Nickel cataly...
3  Disruption of c-Kit Signaling in KitW-sh/W-sh ...  ...                                                 []
4  Ce3+-ion-induced visible-light photocatalytic ...  ...                                                 []

[5 rows x 5 columns]
[2024-05-10T10:12:27.431+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T10:12:27.431+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/clean_data.py", line 63, in clean_api_data
    df = df.apply(lambda x: cleanse_unicode(x) if x.name == 'title' else x)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 10034, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 837, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 965, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/apply.py", line 981, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/clean_data.py", line 63, in <lambda>
    df = df.apply(lambda x: cleanse_unicode(x) if x.name == 'title' else x)
                            ^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/clean_data.py", line 8, in cleanse_unicode
    if not s:
           ^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 1519, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
[2024-05-10T10:12:27.450+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=clean_api_data, run_id=manual__2024-05-10T09:58:46.082243+00:00, execution_date=20240510T095846, start_date=20240510T101227, end_date=20240510T101227
[2024-05-10T10:12:27.461+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 363 for task clean_api_data (The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().; 676)
[2024-05-10T10:12:27.475+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T10:12:27.491+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T10:12:27.492+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
