[2024-05-10T12:51:56.735+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-10T12:51:56.760+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.divide_data manual__2024-05-10T10:18:14.377791+00:00 [queued]>
[2024-05-10T12:51:56.768+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.divide_data manual__2024-05-10T10:18:14.377791+00:00 [queued]>
[2024-05-10T12:51:56.769+0000] {taskinstance.py:2306} INFO - Starting attempt 106 of 109
[2024-05-10T12:51:56.779+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): divide_data> on 2024-05-10 10:18:14.377791+00:00
[2024-05-10T12:51:56.786+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7912) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-10T12:51:56.787+0000] {standard_task_runner.py:63} INFO - Started process 7914 to run task
[2024-05-10T12:51:56.786+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'divide_data', 'manual__2024-05-10T10:18:14.377791+00:00', '--job-id', '527', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp67062tnz']
[2024-05-10T12:51:56.787+0000] {standard_task_runner.py:91} INFO - Job 527: Subtask divide_data
[2024-05-10T12:51:56.798+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-10T12:51:56.827+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline.divide_data manual__2024-05-10T10:18:14.377791+00:00 [running]> on host dbfcb70dcca2
[2024-05-10T12:51:56.924+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='divide_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T10:18:14.377791+00:00' AIRFLOW_CTX_TRY_NUMBER='106' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-10T10:18:14.377791+00:00'
[2024-05-10T12:51:56.925+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-10T12:51:57.134+0000] {logging_mixin.py:188} INFO - Index(['title', 'affiliation_name', 'affiliation_country', 'publication_year',
       'keywords'],
      dtype='object')
[2024-05-10T12:51:57.137+0000] {logging_mixin.py:188} INFO - 0        None
1        None
2        None
3        None
4        None
         ... 
21132    None
21133    None
21134    None
21135    None
21136    None
Name: publication_year, Length: 21137, dtype: object
[2024-05-10T12:51:57.140+0000] {logging_mixin.py:188} INFO - 0        None
1        None
2        None
3        None
4        None
         ... 
21132    None
21133    None
21134    None
21135    None
21136    None
Name: publication_year, Length: 21137, dtype: object
[2024-05-10T12:51:58.542+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-10T12:51:58.543+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/divide_data.py", line 37, in divide_data
    title_keywords_year(df, file_path_to_upload)
  File "/opt/airflow/dags/tasks/divide_data.py", line 55, in title_keywords_year
    if len(keywords) > 2:
       ^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
[2024-05-10T12:51:58.555+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=divide_data, run_id=manual__2024-05-10T10:18:14.377791+00:00, execution_date=20240510T101814, start_date=20240510T125156, end_date=20240510T125158
[2024-05-10T12:51:58.565+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 527 for task divide_data (object of type 'NoneType' has no len(); 7914)
[2024-05-10T12:51:58.606+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-10T12:51:58.623+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-10T12:51:58.625+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
